### PR TITLE
some typo fixes

### PR DESCRIPTION
**Pull request by vlajos**
some typo fixes.
mostly non living code. but some constant, function, variable and file also.

### CODE REVIEW

**Comment by vlajos** [comment]
found some bugs... At the beginning of the next week I will fix them. ("carefully" is worst than were before...)

**Comment by vlajos** [comment]
fixed known "bugs". I don't know more unfortunate unfixed misspellings introduced

**Comment by vlajos** [comment]
I created a small tool for fixing similar cosmetic issues: https://github.com/vlajos/misspell_fixer
Maybe it is more convenient to use it directly instead of merging the pull request.

**Comment by ehsan** [comment]
@vlajos Thanks for your patches.  We currently do not accept pull requests.  Please see https://developer.mozilla.org/en-US/docs/Developer_Guide/How_to_Submit_a_Patch on how to submit your patches to the Mozilla project.  Thanks!

**Comment by vlajos** [comment]
I filled a patch/bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=884524

**Pull request closed without merging**
