### PR TITLE
Bug 743359 - Adding jetpack commonjs module loader to toolkit.

### PR DESCRIPTION
**Pull request by Gozala**
This change adds add-on sdk CommonJS module loader to toolkit.

### CODE REVIEW

**Comment by Gozala** [comment]
@Mossop this is still work in progress patch as I need to apply some of the changes we have discussed today to the loader.

**Comment by ehsan** [comment]
This repository is a read-only mirror of the mozilla-central Mercurial repository.  Please file a bug on bugzilla.mozilla.org, attach a patch, get reviews and land your patch in the Mercurial repository.

Thanks!

**Comment by Gozala** [comment]
@ehsan I'm aware it's read-only we agreed with a reviewer of this patch @Mossop to use pull request just as a tool get patch in an acceptable state. Change itself when accepted will be landed as patch on mozilla-central HG repository.

Please reopen.

**Comment by ehsan** [comment]
I'm not sure how merging this pull request will help you.  It will surely screw up the update scripts that I have for this repo!

**Comment by Mossop** [comment]
There's no intention to merge this pull request, just to use it as a way to do the review rather than in bugzilla comments

**Comment by Gozala** [comment]
Once patch is ready we will just apply https://github.com/mozilla/mozilla-central/pull/2.patch to HG mozilla-central

**Comment by ehsan** [comment]
Oh, OK.  So as long as you guys don't want me to merge this, please feel free to do all sorts of review related work here.  Also, if reopening is needed please feel free to do so, but IIRC you can still review stuff on closed issues as well.

**Pull request closed without merging**
